// Program.cs -- Charger Greetings audio asset preparation.
//
// Usage:  AudioPrep.exe <sourceRoot> <outputDir> <reportPath>
//
// Stage 1  Analyse every candidate MP3 in the source folder and print an
//          objective comparison (LUFS, true peak, DC offset, silence, clipping)
//          so the choice of "which recording ships" is evidence-based.
// Stage 2  Master the two chosen recordings into the shipping assets:
//          DC removal -> silence trim -> fades -> loudness normalisation with a
//          true-peak ceiling -> 16-bit PCM WAV.
//
// The originals are never modified; everything is written to <outputDir>.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace AudioPrep
{
    internal sealed class Measurement
    {
        public string Label;
        public string File;
        public int SampleRate;
        public int Channels;
        public double Duration;
        public double Lufs;
        public double SamplePeakDb;
        public double TruePeakDb;
        public double DcOffset;
        public double LeadingSilence;
        public double TrailingSilence;
        public int ClippedSamples;
    }

    internal static class Program
    {
        // Mastering targets ------------------------------------------------
        // -16 LUFS is the usual landing zone for short spoken UI audio: loud
        // enough to be heard over a room at moderate system volume, quiet
        // enough that it never startles. Both clips land on the same number,
        // which is the whole point -- they must feel equally loud.
        private const double TargetLufs = -16.0;

        // -1.0 dBTP leaves headroom for inter-sample overshoot in the playback
        // chain's resampler. The assets ship as PCM and are never re-encoded,
        // so the usual -1.5 dB lossy-codec allowance is not needed.
        private const double TruePeakCeilingDb = -1.0;

        private const double FadeInSeconds = 0.008;
        private const double FadeOutSeconds = 0.030;
        private const double LeadPadSeconds = 0.020;
        private const double TrimMarginSeconds = 0.030;

        private static int Main(string[] args)
        {
            if (args.Length < 3)
            {
                Console.Error.WriteLine("usage: AudioPrep <sourceRoot> <outputDir> <reportPath>");
                return 2;
            }

            string sourceRoot = args[0];
            string outputDir = args[1];
            string reportPath = args[2];

            try
            {
                Directory.CreateDirectory(outputDir);
                Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(reportPath)));

                StringBuilder report = new StringBuilder();
                report.AppendLine("# Audio asset report");
                report.AppendLine();
                report.AppendLine("Generated by `tools/AudioPrep` on "
                    + DateTime.Now.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture)
                    + " using Windows Media Foundation for decoding and ITU-R BS.1770-4 for loudness.");
                report.AppendLine();

                // ---------------------------------------------------- Stage 1
                Console.WriteLine("=== Stage 1: candidate analysis ===");
                List<Measurement> candidates = new List<Measurement>();
                string[] mp3s = Directory.GetFiles(sourceRoot, "*.mp3", SearchOption.TopDirectoryOnly);
                Array.Sort(mp3s, StringComparer.OrdinalIgnoreCase);

                foreach (string f in mp3s)
                {
                    try
                    {
                        DecodedAudio a = MediaFoundation.Decode(f);
                        Measurement m = Analyse(Path.GetFileName(f), Path.GetFileName(f), a);
                        candidates.Add(m);
                        PrintMeasurement(m);
                    }
                    catch (Exception ex)
                    {
                        Console.Error.WriteLine("  !! " + Path.GetFileName(f) + " : " + ex.Message);
                    }
                }

                report.AppendLine("## 1. Source candidates (as found, unmodified)");
                report.AppendLine();
                AppendTable(report, candidates);
                report.AppendLine();

                // ---------------------------------------------------- Stage 2
                Console.WriteLine();
                Console.WriteLine("=== Stage 2: mastering ===");

                List<string[]> jobs = new List<string[]>();
                // { source file name, output base name, spoken phrase }
                jobs.Add(new string[] {
                    "मालिक, प्रणाम.mp3",
                    "power_connected",
                    "मालिक, प्रणाम" });
                jobs.Add(new string[] {
                    "फिर मिलते हैं, मालिक.mp3",
                    "power_disconnected",
                    "फिर मिलते हैं, मालिक" });

                List<Measurement> mastered = new List<Measurement>();
                bool anyMissing = false;

                // Pass A -- condition each clip (DC, trim, fades) and measure it.
                // Gain is deliberately NOT applied yet: the two clips must end up
                // at exactly the same loudness, so the final level can only be
                // decided once both clips' peak headroom is known.
                List<float[]> buffers = new List<float[]>();
                List<int> rates = new List<int>();
                List<string[]> live = new List<string[]>();
                double achievable = TargetLufs;

                foreach (string[] job in jobs)
                {
                    string src = Path.Combine(sourceRoot, job[0]);
                    if (!File.Exists(src))
                    {
                        Console.Error.WriteLine("  MISSING SOURCE: " + src);
                        anyMissing = true;
                        continue;
                    }

                    DecodedAudio a = MediaFoundation.Decode(src);
                    float[] conditioned = Condition(ToMono(a.Samples, a.Channels), a.SampleRate);

                    double lufs = Loudness.MeasureLufs(conditioned, 1, a.SampleRate);
                    double tpLin = Loudness.MeasureTruePeakLinear(conditioned, 1);
                    double tpDb = tpLin > 0.0 ? 20.0 * Math.Log10(tpLin) : -120.0;

                    // Loudest this clip can be without breaching the peak ceiling.
                    double headroom = TruePeakCeilingDb - tpDb;
                    double clipCeilingLufs = lufs + headroom;
                    if (clipCeilingLufs < achievable) achievable = clipCeilingLufs;

                    Console.WriteLine(string.Format(CultureInfo.InvariantCulture,
                        "  {0,-28} conditioned: {1:0.0} LUFS, {2:0.0} dBTP -> can reach {3:0.0} LUFS",
                        Truncate(job[1], 28), lufs, tpDb, clipCeilingLufs));

                    buffers.Add(conditioned);
                    rates.Add(a.SampleRate);
                    live.Add(job);
                }

                if (achievable < TargetLufs - 0.05)
                {
                    Console.WriteLine(string.Format(CultureInfo.InvariantCulture,
                        "  Peak headroom limits both clips to {0:0.0} LUFS (target was {1:0.0}).",
                        achievable, TargetLufs));
                }

                // Pass B -- apply the common final level and write the assets.
                for (int i = 0; i < live.Count; i++)
                {
                    string[] job = live[i];
                    string outWav = Path.Combine(outputDir, job[1] + ".wav");

                    double lufs = Loudness.MeasureLufs(buffers[i], 1, rates[i]);
                    double gain = 1.0;
                    if (!double.IsNegativeInfinity(lufs) && !double.IsNaN(lufs))
                        gain = Math.Pow(10.0, (achievable - lufs) / 20.0);

                    float[] final = new float[buffers[i].Length];
                    for (int k = 0; k < final.Length; k++)
                        final[k] = (float)(buffers[i][k] * gain);

                    WavIo.WritePcm16(outWav, final, rates[i], 1);

                    DecodedAudio verify = MediaFoundation.Decode(outWav);
                    Measurement m = Analyse(job[2], job[1] + ".wav", verify);
                    mastered.Add(m);

                    Console.WriteLine(string.Format(CultureInfo.InvariantCulture,
                        "  {0}  ->  {1}.wav  ({2:+0.00;-0.00} dB)", job[0], job[1],
                        20.0 * Math.Log10(gain)));
                    PrintMeasurement(m);
                }

                report.AppendLine("## 2. Shipping assets (mastered)");
                report.AppendLine();
                report.AppendLine("Target: **" + TargetLufs.ToString("0.0", CultureInfo.InvariantCulture)
                    + " LUFS** integrated, true peak ceiling **"
                    + TruePeakCeilingDb.ToString("0.0", CultureInfo.InvariantCulture) + " dBTP**, "
                    + "16-bit PCM mono WAV. Gain is applied as a single constant "
                    + "scale factor -- no compression or limiting -- so the recordings "
                    + "cannot be distorted by this process.");
                report.AppendLine();
                AppendTable(report, mastered);
                report.AppendLine();

                if (mastered.Count == 2)
                {
                    double delta = Math.Abs(mastered[0].Lufs - mastered[1].Lufs);
                    report.AppendLine("Perceived-loudness difference between the two shipping clips: **"
                        + delta.ToString("0.00", CultureInfo.InvariantCulture)
                        + " LU** (below the ~1 LU threshold at which a listener notices a level change).");
                    report.AppendLine();
                    Console.WriteLine();
                    Console.WriteLine("  Loudness match between assets: "
                        + delta.ToString("0.00", CultureInfo.InvariantCulture) + " LU");
                }

                File.WriteAllText(reportPath, report.ToString(), new UTF8Encoding(false));
                Console.WriteLine();
                Console.WriteLine("Report written: " + reportPath);

                return anyMissing ? 1 : 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("FATAL: " + ex);
                return 3;
            }
            finally
            {
                MediaFoundation.Shutdown();
            }
        }

        // ------------------------------------------------------------ analysis
        private static Measurement Analyse(string label, string file, DecodedAudio a)
        {
            Measurement m = new Measurement();
            m.Label = label;
            m.File = file;
            m.SampleRate = a.SampleRate;
            m.Channels = a.Channels;
            m.Duration = a.Duration;
            m.Lufs = Loudness.MeasureLufs(a.Samples, a.Channels, a.SampleRate);
            m.SamplePeakDb = Loudness.MeasureSamplePeakDb(a.Samples);
            m.TruePeakDb = Loudness.MeasureTruePeakDb(a.Samples, a.Channels);

            double sum = 0.0;
            int clipped = 0;
            for (int i = 0; i < a.Samples.Length; i++)
            {
                sum += a.Samples[i];
                if (Math.Abs(a.Samples[i]) >= 0.9999f) clipped++;
            }
            m.DcOffset = a.Samples.Length > 0 ? sum / a.Samples.Length : 0.0;
            m.ClippedSamples = clipped;

            float[] mono = ToMono(a.Samples, a.Channels);
            int first, last;
            FindSpeechBounds(mono, a.SampleRate, out first, out last);
            m.LeadingSilence = (double)first / a.SampleRate;
            m.TrailingSilence = (double)(mono.Length - 1 - last) / a.SampleRate;
            return m;
        }

        private static void PrintMeasurement(Measurement m)
        {
            Console.WriteLine(string.Format(CultureInfo.InvariantCulture,
                "  {0,-34} {1,6:0.00}s  {2,5}Hz {3}ch  {4,7:0.0} LUFS  peak {5,6:0.0} dBFS  TP {6,6:0.0} dBTP  DC {7,8:0.00000}  lead {8,5:0.000}s tail {9,5:0.000}s  clipped {10}",
                Truncate(m.File, 34), m.Duration, m.SampleRate, m.Channels,
                m.Lufs, m.SamplePeakDb, m.TruePeakDb, m.DcOffset,
                m.LeadingSilence, m.TrailingSilence, m.ClippedSamples));
        }

        private static string Truncate(string s, int n)
        {
            if (s == null) return "";
            return s.Length <= n ? s : s.Substring(0, n - 1) + "…";
        }

        private static void AppendTable(StringBuilder sb, List<Measurement> rows)
        {
            sb.AppendLine("| File | Dur | Rate | Ch | Integrated | True peak | DC offset | Lead sil. | Tail sil. | Clipped |");
            sb.AppendLine("|---|---|---|---|---|---|---|---|---|---|");
            foreach (Measurement m in rows)
            {
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "| `{0}` | {1:0.00}s | {2} Hz | {3} | {4:0.0} LUFS | {5:0.0} dBTP | {6:0.00000} | {7:0.000}s | {8:0.000}s | {9} |",
                    m.File, m.Duration, m.SampleRate, m.Channels,
                    m.Lufs, m.TruePeakDb, m.DcOffset,
                    m.LeadingSilence, m.TrailingSilence, m.ClippedSamples));
            }
        }

        // ----------------------------------------------------------- mastering
        private static float[] ToMono(float[] interleaved, int channels)
        {
            if (channels == 1) return (float[])interleaved.Clone();
            int frames = interleaved.Length / channels;
            float[] mono = new float[frames];
            for (int i = 0; i < frames; i++)
            {
                double s = 0.0;
                for (int c = 0; c < channels; c++) s += interleaved[i * channels + c];
                mono[i] = (float)(s / channels);
            }
            return mono;
        }

        /// <summary>
        /// Locates the first and last sample that carry speech, using a 10 ms
        /// moving RMS. The floor is 40 dB below the clip's own peak but never
        /// below -50 dBFS, so quiet room tone is trimmed while soft consonants
        /// at the start of a word survive.
        /// </summary>
        private static void FindSpeechBounds(float[] mono, int sampleRate, out int first, out int last)
        {
            first = 0;
            last = mono.Length - 1;
            if (mono.Length == 0) return;

            double peak = 0.0;
            for (int i = 0; i < mono.Length; i++)
            {
                double a = Math.Abs(mono[i]);
                if (a > peak) peak = a;
            }
            if (peak <= 0.0) return;

            double threshold = Math.Max(peak * Math.Pow(10.0, -40.0 / 20.0),
                                        Math.Pow(10.0, -50.0 / 20.0));

            int win = Math.Max(1, (int)(sampleRate * 0.010));
            double[] energy = new double[mono.Length];
            double running = 0.0;
            for (int i = 0; i < mono.Length; i++)
            {
                running += mono[i] * mono[i];
                if (i >= win) running -= mono[i - win] * mono[i - win];
                energy[i] = Math.Sqrt(running / Math.Min(i + 1, win));
            }

            int f = 0;
            while (f < mono.Length && energy[f] < threshold) f++;
            int l = mono.Length - 1;
            while (l > f && energy[l] < threshold) l--;

            if (f >= mono.Length) { first = 0; last = mono.Length - 1; return; }

            // The moving RMS lags the signal by roughly one window, so pull the
            // start back by the window length before applying the safety margin.
            first = Math.Max(0, f - win);
            last = Math.Min(mono.Length - 1, l);
        }

        /// <summary>
        /// Conditions a clip: DC removal, silence trim, lead pad and edge fades.
        /// Level is intentionally left untouched -- see the two-pass comment in
        /// Main for why gain is applied only after both clips are measured.
        /// </summary>
        private static float[] Condition(float[] mono, int sampleRate)
        {
            // 1. Remove DC offset -- it wastes headroom and can thump on small speakers.
            double mean = 0.0;
            for (int i = 0; i < mono.Length; i++) mean += mono[i];
            if (mono.Length > 0) mean /= mono.Length;
            float[] work = new float[mono.Length];
            for (int i = 0; i < mono.Length; i++) work[i] = (float)(mono[i] - mean);

            // 2. Trim silence with a margin so nothing is clipped off the words.
            int first, last;
            FindSpeechBounds(work, sampleRate, out first, out last);
            int margin = (int)(sampleRate * TrimMarginSeconds);
            first = Math.Max(0, first - margin);
            last = Math.Min(work.Length - 1, last + margin);
            int len = Math.Max(1, last - first + 1);

            // 3. Prepend a short pad. Some Bluetooth and USB endpoints need a few
            //    milliseconds to wake, and would otherwise swallow the first syllable.
            int pad = (int)(sampleRate * LeadPadSeconds);
            float[] trimmed = new float[pad + len];
            Array.Copy(work, first, trimmed, pad, len);

            // 4. Fades to guarantee no click at either edge.
            int fadeIn = Math.Min((int)(sampleRate * FadeInSeconds), trimmed.Length);
            for (int i = 0; i < fadeIn; i++)
                trimmed[pad + i] *= (float)((double)i / fadeIn);
            int fadeOut = Math.Min((int)(sampleRate * FadeOutSeconds), trimmed.Length);
            for (int i = 0; i < fadeOut; i++)
                trimmed[trimmed.Length - 1 - i] *= (float)((double)i / fadeOut);

            return trimmed;
        }
    }
}
